#!/usr/bin/env bash
A Bash script that configures an Ubuntu server

sudo cp /etc/hosts /etc/hosts.bak
sudo sed -i 's/facebook\.com/8.8.8.8 facebook.com/g' /etc/hosts

sudo systemd-resolve --flush-caches

